global_floods_django_app/MainPage/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.index,name='index'),
  path('pick/', views.pick, name='pick'),
  path('draw/', views.draw, name='draw'),
  path('upload/', views.upload, name='upload'),
  path('result/', views.result, name='result')]

global_floods_django_app/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'global_floods_django_app'

urlpatterns = [
  path('', views.index, name="index"),
  path('pick/', views.pick, name='pick'),
  path('draw/', views.draw, name='draw'),
  path('upload/', views.upload, name='upload'),
  path('result/', views.result, name='result'),
  path('/admin/', admin.site.urls)]

global_floods_django_app/MainPage/models.py
from django.db import models

# Create your models here.

global_floods_django_app/models.py
from django.contrib.gis import forms
from django.contrib.gis.db import models
# Create your models here.

class Bank(models.Model):
    name = models.CharField(max_length=20)
    poly = models.PolygonField()

    def __str__(self):
        return self.name

global_floods_django_app/forms.py
from django.contrib.gis import forms
from leaflet.forms.widgets import LeafletWidget




class OSmapForm(forms.Form):
    poly = forms.PolygonField(widget =
        forms.OSMWidget(attrs = {'map_width': 1024, 'map_height': 600}))

global_floods_django_app/views.py
from django.shortcuts import render,redirect

# Create your views here.
# coding:utf-8
from django.http import HttpResponse
from django.template import loader,Context
from django.views.generic import TemplateView
from .read_MoM_point import *
import folium
import datetime
from .forms import *
from .models import *
import json
from django.contrib import messages
from django_tables2.tables import Table
import os
import jinja2
import shapely

s_date=''
e_date=''
poly = '1'

def index(request):
    context = {'map':'load failed'}
    map = init_map()
    m = map._repr_html_()
    context = {'map': m}
    return render(request, 'global_floods_django_app/index.html', context)

def pick(request):
    map,df = pick_map()
    m = map._repr_html_()
    context = {'map': m}
    if request.method == "POST":
        if 'run-model' in request.POST:
            lat = request.COOKIES.get('lat')
            lng = request.COOKIES.get('lng')
            pfaf = df.loc[(df['Lat']==float(lat)) & (df['Lon']==float(lng))]
            if len(pfaf) >1:
                pfaf = pfaf.iloc[0]
            sim_geo = gpd.GeoSeries(pfaf['geometry_y']).simplify(tolerance=0.001)
            geo_j = sim_geo.to_json()
            s_date = request.POST.get("pre-event")
            e_date = request.POST.get("post-event")
            if s_date <= e_date:
                messages.error(request,'Please fill both pre-event and post-event date! Also please make sure pre is befor after!')
            # pred(s_date, e_date, poly=geo_j)
            return render(request, 'global_floods_django_app/pick.html',context)
        elif 'download' in request.POST:
            x = 1
    return render(request, 'global_floods_django_app/pick.html', context)

def draw(request):
    map = draw_map()
    m = map._repr_html_()
    context = {'map': m}
    if request.method == "POST":
        if 'run-model' in request.POST:
            geo_info = request.COOKIES.get('geometry')
            s_date = request.POST.get("pre-event")
            e_date = request.POST.get("post-event")
            if s_date <= e_date:
                messages.error(request,'Please fill both pre-event and post-event date! Also please make sure pre is befor after!')
            # pred(s_date, e_date, poly=geo_info)
            return render(request, 'global_floods_django_app/draw.html',context)
        elif 'download' in request.POST:
            x=1
    return render(request, 'global_floods_django_app/draw.html', context)

def upload(request):
    global poly
    context = {'map':'null'}
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    TEMP_FILE = os.path.join(BASE_DIR, "global_floods_django_app", "static/temp_file", "footprint.geojson")
    if request.method == "POST":
        if 'ufile' in request.POST:
            File = request.FILES.get("myfile",None)
            if File is None:
                messages.error(request,"There is no chosen file ")
            else:
                with open(TEMP_FILE, 'wb+') as f:
                    for chunk in File.chunks():
                        f.write(chunk)
            map = show_map()
            m = map._repr_html_()
            context = {'map': m}
            return render(request, 'global_floods_django_app/upload.html', context)
        elif 'run-model' in request.POST:
            s_date = request.POST.get("pre-event")
            e_date = request.POST.get("post-event")
            if s_date <= e_date:
                messages.error(request,'Please fill both pre-event and post-event date! Also please make sure pre is befor after!')
            # pred(s_date, e_date, poly=None)
            return render(request, 'global_floods_django_app/upload.html', context)
        elif 'download' in request.POST:
            x=1
    return render(request, 'global_floods_django_app/upload.html')

def result(request):
    map = pick_map()
    m = map._repr_html_()
    context = {'map': m}
    return render(request, 'global_floods_django_app/result.html', context)

global_floods_django_app/templates/global_floods_django_app/draw.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Global Flooding Monitor Gateway</title>
    <style>
    a:link{color:black;}
    a:visited{color:black;}
  </style>
  {{ form.media }}
</head>
<body>
  <h1 id="test">Welcome to the Global Flooding Impact Monitoring Gateway!</h1>
  <p> Welcom to the Global Flooding Impact Monitoring Gateway, here you can use the GloFIM Apps to predict the flooding affection.</p>
  <div>
    <h2>Low resolusion impact monitoring</h2><br>
    <a href = "{% url 'global_floods_django_app:pick' %}"><button>Connecting to MoM track2 Output</button></a>
    <a href = "{% url 'global_floods_django_app:draw' %}"><button>User-defined: Polygon</button></a>
    <a href = "{% url 'global_floods_django_app:upload' %}"><button>User-defined: GeoJson</button></a>
    <br>
    <h2>High resolusion impact monitoring</h2>
  </div>
  {% if messages %}
       <script>
           {% for msg in messages %}
               alert('{{ msg.message }}');
           {% endfor %}
       </script>
   {% endif %}
  <div class="map">
    <form id = "geometry" method="post" action="">
        {% csrf_token %}
        <h3>Please choose the date for flooding date</h3>
        <br>
        the date for drawed area:<br>
        Pre-event date:<input type="date" name="pre-event"><br>
        Post-event date:<input type="date" name="post-event"><br>
        Please draw your interested area and click "submit" button <br>
        <div name="poly">
        {{ map|safe }}
        </div>
        {% if result %}
          <p><input type="submit" value="Download Result" name = "download"></p>
        {% else %}
          <p><input type="submit" value="Run Model" name = "run-model"></p>
        {% endif %}
    </form>
  </div>
</body>
<script src="js/script.js" type="text/javascript"></script>
</html>

global_floods_django_app/templates/global_floods_django_app/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="main-content-wrapper">
    <main class="main-content">
        <div class="container-fluid">
            <h1>Welcome to {{ project_name }}</h1>
        </div>
    </main>
</div>
{% endblock content %}

{% block scripts %}
<!-- Load the AiravataAPI JavaScript SDK (optional) -->
<script src="{% static 'django_airavata_api/dist/airavata-api.js' %}"></script>
<script>
    const { models, services, session, utils } = AiravataAPI;

    // Your code here ...
    // Example code: AiravataAPI JavaScript SDK
    // Use the JavaScript SDK to make REST API calls. For example, load the most
    // recent 5 experiments created by the current user:
    //
    // services.ExperimentSearchService
    //         .list({limit: 5,
    //             [models.ExperimentSearchFields.USER_NAME.name]: session.Session.username,
    //         })
    //         .then(data => {
    //             const experiments = data.results;
    //             // Do something with the experiments ...
    //         });
    //
    // See the Custom UI tutorial for more examples:
    // https://apache-airavata-django-portal.readthedocs.io/en/latest/tutorial/custom_ui_tutorial/#tutorial-exercise-create-a-custom-django-app
    // To see what is in the `AiravataAPI` JavaScript library, take a look at
    // it's index.js file:
    // https://github.com/apache/airavata-django-portal/blob/master/django_airavata/apps/api/static/django_airavata_api/js/index.js
</script>
{% endblock scripts %}

global_floods_django_app/templates/global_floods_django_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Global Flooding Monitor Gateway</title>
    <style>
    a:link{color:black;}
    a:visited{color:red;}
  </style>
</head>
<body>
  <h1>Welcome to the Global Flooding Impact Monitoring Gateway!</h1>
  <p> Welcom to the Global Flooding Impact Monitoring Gateway, here you can use the GloFIM Apps to predict the flooding affection.</p>
  <div>
    <h2>Low resolusion impact monitoring</h2><br>
    <a href = "{% url 'global_floods_django_app:pick' %}"><button>Connecting to MoM track2 Output</button></a>
    <a href = "{% url 'global_floods_django_app:draw' %}"><button>User-defined: Polygon</button></a>
    <a href = "{% url 'global_floods_django_app:upload' %}"><button>User-defined: GeoJson</button></a>
    <br>
    <h2>High resolusion impact monitoring</h2>
  </div>
  <div class="map">
  {{ map|safe }}
  </div>
</body>
</html>

global_floods_django_app/templates/global_floods_django_app/map.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="main-content-wrapper">
    <main class="main-content">
        <div class="container-fluid">
            <div id="map"></div>
        </div>
    </main>
</div>
{% endblock content %}

{% block css %}
<link rel="stylesheet" href="{% static 'global_floods_django_app/leaflet/leaflet.css' %}" />

<style>
.container-fluid, #map {
    height: 100%;
}
.main-content, .container-fluid {
    padding: 0;
    margin: 0;
    max-width: none;
}
</style>
{% endblock css %}

{% block scripts %}
<script src="{% static 'global_floods_django_app/leaflet/leaflet.js' %}"></script>
<!-- Load the AiravataAPI JavaScript SDK (optional) -->
<script src="{% static 'django_airavata_api/dist/airavata-api.js' %}"></script>
<script>
    const { models, services, session, utils } = AiravataAPI;

    // Your code here ...
    // Example code: AiravataAPI JavaScript SDK
    // Use the JavaScript SDK to make REST API calls. For example, load the most
    // recent 5 experiments created by the current user:
    //
    // services.ExperimentSearchService
    //         .list({limit: 5,
    //             [models.ExperimentSearchFields.USER_NAME.name]: session.Session.username,
    //         })
    //         .then(data => {
    //             const experiments = data.results;
    //             // Do something with the experiments ...
    //         });
    //
    // See the Custom UI tutorial for more examples:
    // https://apache-airavata-django-portal.readthedocs.io/en/latest/tutorial/custom_ui_tutorial/#tutorial-exercise-create-a-custom-django-app
    // To see what is in the `AiravataAPI` JavaScript library, take a look at
    // it's index.js file:
    // https://github.com/apache/airavata-django-portal/blob/master/django_airavata/apps/api/static/django_airavata_api/js/index.js


    const OpenStreetMap_Mapnik = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    });
    const mymap = L.map('map');//.setView([39.74739, -105], 13);
    OpenStreetMap_Mapnik.addTo(mymap);

    fetch("https://raw.githubusercontent.com/Global-Flood-Assessment/ModelOfModels/master/tools/most_severe_flood_20210127.geojson")
        .then(resp => resp.json())
        .then(geojson => {
            const layer = L.geoJSON(geojson).addTo(mymap);
            mymap.fitBounds(layer.getBounds());
        });
</script>
{% endblock scripts %}

global_floods_django_app/templates/global_floods_django_app/pick.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GloFIM Gateway</title>
    <style>
    a:link{color:black;}
    a:visited{color:black;}
  </style>
</head>
<body>
  <h1>Welcome to the Global Flooding Impact Monitoring Gateway!</h1>
  <p> Welcom to the Global Flooding Impact Monitoring Gateway, here you can use the GloFIM Apps to predict the flooding affection.</p>
  <div>
    <h2>Low resolusion impact monitoring</h2><br>
    <a href = "{% url 'global_floods_django_app:pick' %}"><button>Connecting to MoM track2 Output</button></a>
    <a href = "{% url 'global_floods_django_app:draw' %}"><button>User-defined: Polygon</button></a>
    <a href = "{% url 'global_floods_django_app:upload' %}"><button>User-defined: GeoJson</button></a>
    <br>
    <h2>High resolusion impact monitoring</h2>
  </div>
  {% if messages %}
       <script>
           {% for msg in messages %}
               alert('{{ msg.message }}');
           {% endfor %}
       </script>
   {% endif %}

  <div class="map">
    <form method="post" action="">
        {% csrf_token %}
        <h3>Please choose the date for MoM track2 output file</h3>
        <br>
        the date for MoM track2 output file:<br>
        Pre-event date:<input type="date" name="pre-event"><br>
        Post-event date:<input type="date" name="post-event"><br>
        Please click your interested event from the left map and details will show in right map; <br>
        {{ map|safe }}
        {% if result %}
          <p><input type="submit" value="Download Result" name = "download"></p>
        {% else %}
          <p><input type="submit" value="Run Model" name = "run-model"></p>
        {% endif %}
      </form>
  </div>
</body>
</html>

global_floods_django_app/templates/global_floods_django_app/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Global Flooding Monitor Gateway</title>
    <style>
    a:link{color:black;}
    a:visited{color:black;}
  </style>
</head>
<body>
  <h1>Welcome to the Global Flooding Impact Monitoring Gateway!</h1>
  <p> Welcom to the Global Flooding Impact Monitoring Gateway, here you can use the GloFIM Apps to predict the flooding affection.</p>
  <div>
    <h2>Low resolusion impact monitoring</h2><br>
    <a href = "{% url 'global_floods_django_app:pick' %}"><button>Connecting to MoM track2 Output</button></a>
    <a href = "{% url 'global_floods_django_app:draw' %}"><button>User-defined: Polygon</button></a>
    <a href = "{% url 'global_floods_django_app:upload' %}"><button>User-defined: GeoJson</button></a>
    <br>
    <h2>High resolusion impact monitoring</h2>
  </div>
  <div class="map">
    <form method="post" action="">
        {% csrf_token %}
        The Random Forest prediction map; <br>
        {{ map|safe }}
        <p><input type="submit" value="Download" name = "download"></p>
      </form>
  </div>
</body>
</html>

global_floods_django_app/templates/global_floods_django_app/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Global Flooding Monitor Gateway</title>
    <style>
    a:link{color:black;}
    a:visited{color:black;}
  </style>
</head>
<body>
  <h1>Welcome to the Global Flooding Impact Monitoring Gateway!</h1>
  <p> Welcom to the Global Flooding Impact Monitoring Gateway, here you can use the GloFIM Apps to predict the flooding affection.</p>
  <div>
    <h2>Low resolusion impact monitoring</h2><br>
    <a href = "{% url 'global_floods_django_app:pick' %}"><button>Connecting to MoM track2 Output</button></a>
    <a href = "{% url 'global_floods_django_app:draw' %}"><button>User-defined: Polygon</button></a>
    <a href = "{% url 'global_floods_django_app:upload' %}"><button>User-defined: GeoJson</button></a>
    <br>
    <h2>High resolusion impact monitoring</h2>
  </div>
  {% if messages %}
       <script>
           {% for msg in messages %}
               alert('{{ msg.message }}');
           {% endfor %}
       </script>
   {% endif %}
  <form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
        <h2>Please upload geojson file and choose pre-event date and post-event date</h2>
        <br>
        Pre-event date:<input type="date" name="pre-event"><br>
        Post-event date:<input type="date" name="post-event"><br>
        Please upload Geojson file for your area of interested; <br>
        <input type="file" accept=".geojson" name="myfile"><br>
        <input type="submit" value="upload" name = "ufile">
        {% if result %}
          <p><input type="submit" value="Download Result" name = "download"></p>
        {% else %}
          <p><input type="submit" value="Run Model" name = "run-model"></p>
        {% endif %}
        <div class="map">
        {{ map|safe }}
        </div>
    </form>

</body>
</html>